[정렬] 9월 2일
Altu-Bitu-3/Altu-Bitu-MingyungPark pull request #1
Opened 2022-09-07 05:38 UTC by Parkkate

# 내용&질문
| 정렬 과제 5개 제출합니다.
| 1026번에서 b를 정렬하지않고 기준으로하여 a를 정렬하려 한다면 sort의 cmp를 통해 정렬할 수 있을지, 그렇다면 어떤식으로 cmp함수를 짜야할 지 궁금합니다.
# <기존 제출>
| 문제번호 1026, 1431, 1758, 1946, 11651

2022-09-07 12:27 UTC, jaeseo222 reviewed
**p3. 11651 코드 리뷰 완료**

안녕하세요 민경님 ☺️☺️ 코드를 깔끔하게 작성해주셔서 리뷰 드리기 너무 좋았습니다!
나중에, 코드가 길어졌을 땐 주석으로 보충 설명 해주셔도 좋을 것 같습니다. 🔥🔥
간단한 코멘트 달았으니, 확인 부탁드립니다 !

**수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다!** 수고 많으셨습니다.
감사합니다 ☺️☺️

2022-09-07 12:27 UTC, jaeseo222 commented on 09월 02일 - 정렬/11651.cpp
> +}
p3.

pair을 `sort`하면 **pair의 `first`가 1차, `second`가 2차로 오름차순 정렬** 된다는 것을 정확히 이해해주시고 **pair을 이용한 비교 함수**를 알맞게 구현해주셨네요!! ☺️☺️

📌`pair<int, int>`를 매번 선언하기엔 코드가 너무 길어지기 때문에 `typedef`를 이용하는 방법도 고려해주시면 좋을 것 같습니다!

2022-09-07 18:01 UTC, flowersayo reviewed
1946 코드 리뷰 완료

안녕하세요 민경님 😊 ㅎㅎ
코드를 정말 깔끔하게 잘 작성해주셨어요 완벽합니다..👍
저희 샘플코드랑 다를게 없어서 제가 더 피드백 드릴 부문이 없네용
바로 머지하셔도 될것 같아요! 수고하셨습니다 :)

2022-09-07 18:01 UTC, flowersayo commented on 09월 02일 - 정렬/1946.cpp
> +		vector<pair<int, int>> arr(n);
p3

`typedef pair<int, int> ci;` //pair<int,int> 자료형을 ci 별칭으로 사용함을 정의 하면
`vector <ci> arr(n) 와 같이 간결하게 선언할 수 있습니다ㅎㅎ

2022-09-07 18:01 UTC, flowersayo commented on 09월 02일 - 정렬/1946.cpp
> +}
맞아요!
본 문제는 서류심사 혹은 면접심사 순위 기준으로 정렬해서 나머지 심사 순위를 비교해가며 푸는 문제였어요.
함수화까지 잘해주셨네요 🥰

천천히 합격유무를 판단해보면,
서류 순위 1등은 반드시 뽑힐 수 있어요
서류순위 2등인사람은 서류순위 1등인사람의 면접순위 점수보다 높다면 뽑힐수있어요.
서류순위 3등인사람은 서류순위 1,2 등 인 사람들보다 면접순위점수보다 높다면 뽑힐수 있어요.
서류순위 4등인사람은 서류순위 1,2,3 등 인 사람들보다 면접순위점수보다 높다면 뽑힐수 있죠.
이때 4등을 1,2,3등 각각과 비교하게 되면 O(N2)의 시간복잡도를 가지므로 시간초과가 날꺼에요. 따라서 가장 높은 면접심사 순위를 계속 갱신해서 O(n) 으로 풀이해야하는 문제였어요!

2022-09-07 18:01 UTC, flowersayo commented on 09월 02일 - 정렬/1946.cpp
> +		t--;
p3. 이부분은 while 조건식 안에 넣어서 처리할 수 있을 것 같아요!

2022-09-08 10:51 UTC, jk0527 approved these changes
P3. 1026 코드 리뷰 완료

저희가 준비한 셈플 코드랑 거의 똑같이 코드를 짜주셨어요!! 정말 로직도 좋고 정말 깔끔한 것 같아요! 다 좋은 것 같아요!! 1026은 이대로 머지하셔도 될 것 같아요!!

그리고 b를 정렬하면 안된다고 되어 있기는 한데 저희 샘플 코드도 일단 b를 정렬하고 있습니다. 하지만 만약에 b를 정렬하지 않고 싶으시다면.. b의 크기 순위(rank)를 인덱스로 저장하고 인덱스를 역순으로 a와 곱할 수는 있을 것 같아요.
예를 들어 b의 숫자가 3 5 1이라면 순위는 2 3 1이니까 각각을 a의 2 1 3 번째랑 곱하는 방식으로요! 이해가 되셨을까요?
그냥 제가 한 번 생각해본 건데... 이렇게 하면 인덱스, 즉 순위를 다 기록하고 찾아야 해서 시간 복잡도가 높아질 수는 있을 것 같아요ㅠㅠ

더 궁금하신 것 있으시면 리뷰어를 호출해주세요!!

2022-09-08 10:51 UTC, jk0527 commented on 09월 02일 - 정렬/1026.cpp
> +		cin >> b[i];
저희가 샘플 코드를 제공할 때는 중괄호 생략을 지향하고 있습니다. 물론 코딩테스트에서는 그럴 일이 없겠지만 일반적인 코딩을 할 때는 코드를 수정하는 일이 생길 수도 있어서요! 수정하실 필요는 없고 참고만 해주세요!😄

2022-09-08 15:33 UTC, Minseo10 requested changes
**P1. 1431 코드리뷰 완료**
안녕하세요 민경님! sumNumber함수에서 수정이 필요한 부분이 있네요,,!
그 외에도 사소한 코멘트 몇가지 남겼으니 확인 부탁드려요:) 코드 수정하시면 리뷰어로 불러주세요~!
첫 수업 과제 수고하셨습니다 😄

2022-09-08 15:33 UTC, Minseo10 commented on 09월 02일 - 정렬/1431.cpp
> +		if (a[i] <= '9')
P1: if문에 조건이 하나 더 필요할 것 같아요. '0'보다 큰 경우를 체크하지 않으면 버그가 일어날 가능성이 있습니다,,! 그리고 a[i]를 직접 체크하는 방법 말고도 isdigit함수를 이용하는 방법이 있으니 참고해 주세요~

2022-09-08 15:33 UTC, Minseo10 commented on 09월 02일 - 정렬/1431.cpp
> +		return a < b;
P2:  return 이후의 코드는 실행되지 않으니 어떻게 보면 else문과 같은 역할을 한다고 볼 수 있어요. 굳이 else if문, else문을 사용하지 않고, 세가지 경우 모두 if-return구조를 사용하는 것을 권장합니다!

2022-09-08 15:33 UTC, Minseo10 commented on 09월 02일 - 정렬/1431.cpp
> +		return a.length() < b.length();
P3: 이건 아주 사소한 부분이긴 한데, if문에서 중괄호{}를 사용하는 것을 권장합니다..! 이후에 다른 사람과 협업할 때 중괄호가 있는 편이 코드를 수정하기 용이한 부분이 있어요!

2022-09-09 06:37 UTC, bsa0322 reviewed
**p3. 1758 코드리뷰 완료**
풀이 너무너무 완벽하네요!! 최고입니다 ✨
클린 코드 작성에서,, 의견이 분분한 한 줄 코드 중괄호 생략에 대한 의견 간단히 남겨봤어요 😂
첫 과제 너무 수고하셨습니다 🔥

\+ 1026 질문 주신 부분에 대해 추가 코멘트를 드려보자면, 문제에서는 B를 재배열하지 말라고 했지만, **사실 B를 재배열한 코드 또한 문제의 조건을 만족하고 있어요!** 코드는 B를 재배열하고 있지만 실제론 B는 가만히 있고, 해당 쌍에 맞게 A를 재배열한거라고 생각할 수 있기 때문이죠!!!

2022-09-09 06:37 UTC, bsa0322 commented on 09월 02일 - 정렬/1758.cpp
> +			break;
함수화 해주신 것도, 앞으로의 경우에도 팁을 받을 수 없으므로 끊어주신 것도 완전 좋아요 ✨✨✨

조금 사소한 코멘트를 드리자면, 저희가 중괄호 생략하는 것을 지양하고 있는데요..!! 나중에 코드를 수정할 일이 생길 수도 있고, 특히 협업시에 이런 경우가 생긴다면 충돌이 일어날 수도 있기 때문이에요. 따라서 한 번 고려해봐주셔도 좋을 것 같습니다. 🔥

2022-09-10 15:09 UTC, merged